### ISSUE TITLE
Inpainting isn't confined to changing only the masked area.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [SeargeDP/SeargeSDXL#19] opened 2023-08-03 07:07 UTC
I've just tried the inpainting, for the first time, to remove a "spare hand". It worked, but it also changed the overall image; the person's skin was smoothed out and lost detail, as well as other minor changes throughout the image.
These are the before (with the extra hand) and after (correct number of hands, but lacking the detail of the original) images:
![0002_2nd-pass](https://github.com/SeargeDP/SeargeSDXL/assets/52193044/8935e216-f3d2-40a7-90c9-760d8522223e)
![gen_00004_](https://github.com/SeargeDP/SeargeSDXL/assets/52193044/fc0a942a-fb29-4460-a474-947b4e49551f)

I also tried an upscaled version, with slightly less denoise:
![up_00001_](https://github.com/SeargeDP/SeargeSDXL/assets/52193044/83ac838f-2c53-4b30-8fda-c1a8aeefb8c8)

Perhaps I just misunderstand how inpainting works, but I expected it to only change the masked area and leave the rest intact.

**Comment by SeargeDP** [comment] 2023-08-04 22:41
Did you set the width and height field to the dimensions of your input image?

**Comment by GalaxyTimeMachine** [comment] 2023-08-05 05:41
Not in the example above, but even if I do, it's just the same outcome. The leaves in the background bush, and skin details have been changed.
![ComfyUI_temp_tnfff_00001_](https://github.com/SeargeDP/SeargeSDXL/assets/52193044/0015895c-e035-48ad-baa1-406585e209b0)

**Comment by GalaxyTimeMachine** [comment] 2023-08-05 05:43
Further info... The original image was made using an SD1.5 based model, so it probably has more detail in it from that, but the inpainting should retain the unmasked area details...shouldn't it?

**Comment by SeargeDP** [comment] 2023-08-05 10:09
Yes, it should not touch the areas outside of the mask. Have to look into this, my stuff internally just depends on Comfy default functionality so I need to figure out if that's a general problem or something caused by me incorrectly using some nodes

**Comment by naql** [comment] 2023-08-06 05:50
inpainting is working for me, only affecting masked area

**Comment by SeargeDP** [comment] 2023-08-09 16:02
I think I found a way to improve inpainting a bit and it'll be included in the next update. I'll post here when that's available for testing.

**Comment by SeargeDP** [comment] 2023-08-21 11:15
This should be fixed in the next (upcoming) update

**Closed by SeargeDP** 2023-08-21 11:15 UTC
