### ISSUE TITLE
Image upscale with model not found

### ISSUE THREAD

**Issue by qwerty-qwerty1** [SeargeDP/SeargeSDXL#29] opened 2023-08-06 08:34 UTC
Can someone help me to find the node containing `imageupscalewith model`?
i am using v3.2
![image](https://github.com/SeargeDP/SeargeSDXL/assets/91939399/f236fc62-2f12-4578-afa9-5e4c6887f2cd)

**Comment by SeargeDP** [comment] 2023-08-06 16:13
Can you check 2 things please:
- Did you download and copy all the [files listed here](https://github.com/SeargeDP/SeargeSDXL#direct-downloads)?
- If you are using other custom node extension for ComfyUI, does the problem still occur if you **only** use the Searge-SDXL extension?

**Comment by qwerty-qwerty1** [comment] 2023-08-06 16:31
yeah, i have downloaded 1.0 vae and all other files

**Comment by SeargeDP** [comment] 2023-08-06 17:05
Did you also try the second suggestion, if you have more node extensions installed? I want to figure out if my extension is incompatible with any other extensions, so that I can solve the issue if that's the case.

**Comment by qwerty-qwerty1** [comment] 2023-08-06 17:07
i have many custom nodes
so you are saying that there is some incompatibility issue?

**Comment by SeargeDP** [comment] 2023-08-06 17:11
I don't know that yet, because I don't know what you have installed. If you move the other extensions into another directory and only leave my extension installed, then restart Comfy, does it still cause the issue?
You can copy the other extensions back again after this test and restart again, so that you don't have to re-install them all manually.

**Comment by qwerty-qwerty1** [comment] 2023-08-06 17:30
oh ok
will try

**Comment by qwerty-qwerty1** [comment] 2023-08-08 13:38
I have tested and found that some other custom nodes are interfering and can you please help fix that

**Comment by SeargeDP** [comment] 2023-08-09 07:31
I need more information than that. Which other extensions are incompatible? I don't know if I can fix it until I know where to look and what the problem is.

**Comment by qwerty-qwerty1** [comment] 2023-08-09 16:03
i observed it for 3.4 and 3.2 but did not occur for 2.x

**Comment by SeargeDP** [comment] 2023-08-21 11:16
This should be fixed in the next (upcoming) update

**Closed by SeargeDP** 2023-08-21 11:16 UTC
